name: Primeiro Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout do código
        uses: actions/checkout@v4
    
      - name: Executar Hello World
        run: echo "Hello Github Actions"
      
      - name: Sistema operacional
        run: |
          echo "Sistema Operacional:"
          echo " ${{runner.os}}"
          echo " $(pwd)"
          echo "$(date)"
          echo "$(whoami)"
      
      - name: Listar arquivos do repositorio
        run: ls -lha
      
      - name: Comandos multiplos
        run: |
          echo "Esté é o lab 01 do github actions:"
          echo " ${{runner.os}}"
          echo " $(pwd)"
          echo "$(date)"
          echo "$(whoami)"
        
      - name: Finalizando
        run: |
          echo "Workflow executado com sucesso."
          echo "Pronto para os próximos desafios."